function Bx = fourier_bx(C,C1,C2,C3,xi)
%FOURIER_BX
%    BX = FOURIER_BX(C,C1,C2,C3,W)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    14-Aug-2014 11:01:16

% t2 = sign(w);
% t3 = sqrt(C);
% t4 = 1.0./t2;
% t5 = t3.*t4.*w;
% t6 = 1.0./sqrt(C);
% t7 = abs(w);
% t8 = w.^2;
% t9 = besselkk(1,t5);
% Bx = -C1.*(t8.*besselkk(0,t5).*(2.0./3.0)-t2.*t6.*t9.*w.*(2.0./3.0))+C3.*t6.*t7.*besselkk(1,t3.*t7).*2.0-C2.*t4.*t6.*t8.*t9.*6.666666666666667e-1i;
F4 = 2*abs(xi).*besselk(1,C*abs(xi))/(3*sqrt(C))-2*xi.^2.*besselk(0,C*abs(xi))/3;
F3 = -2*xi.^2.*besselk(1,C*abs(xi))*1i./(3*C*sign(xi));
F2 = sqrt(2/pi)*1/C*abs(xi).*besselk(1,C*abs(xi));
Bx = C1*F4+C2*F3+C3*F2;